# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "dry-types", "~> 0.14.0"
gem "dry-struct", "~> 0.6.0"

gem "rspec", "~> 3.8"

gem "pry", "~> 0.12.2"

gem "dry-validation", "~> 0.13.0"
