# frozen_string_literal: true

ruby "2.5.1"

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


# Added at 2018-09-04 13:31:44 -0700 by ssangervasi:
gem "rspec", "~> 3.8", :groups => [:development, :test]

gem "rubocop", "~> 0.58.2"

gem "pry", "~> 0.11.3", :groups => [:development, :test]
