# frozen_string_literal: true

ruby '2.5.1'

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development, :test do
  gem 'pry', '~> 0.11.3', groups: %i[development test]
  gem 'rspec', '~> 3.8'
  gem 'rubocop', '~> 0.58.2'
  gem 'rubocop-rspec', '~> 1.29', group: [:test]
end
